name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Cache SonarCloud packages'
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: 'Cache Gradle packages'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 'Run Tests'
        run: ./gradlew build test jacocoTestReport

      - name: 'Sonar Scan'
        env:
          # Needed to get PR information, if any
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --debug

      - name: 'Copy coverage for Qodana'
        run: |
          mkdir -p .qodana/code-coverage
          cp ./interceptor-tests/build/reports/jacoco/test/jacocoTestReport.xml .qodana/code-coverage/

      - name: 'Archive coverage data'
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-coverage-data
          path: .qodana/code-coverage

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          pr-mode: true
          args: --apply-fixes
          push-fixes: pull-request


