name: "Build and Test"
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/**.md'
      - '.gitignore'
      - '.github/CODEOWNERS'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**/**.md'
      - '.gitignore'
      - '.github/CODEOWNERS'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5

      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Cache SonarCloud packages'
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: 'Cache Gradle packages'
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 'Run Tests'
        run: ./gradlew build test jacocoTestReport

      - name: 'Sonar Scan'
        env:
          # Needed to get PR information, if any
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Sonar fails for dependabot triggered workflows
        # Let's disable it (we don't expect any code changes anyway)
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: ./gradlew sonar
