name: "Qodana"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/**.md'
      - '.gitignore'
      - '.github/CODEOWNERS'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**/**.md'
      - '.gitignore'
      - '.github/CODEOWNERS'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up JDK"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # Analyze ONLY changed files in a pull request.
          pr-mode: false
          # Use annotation to mark the results in the GitHub user interface.
          use-annotations: true
          # Post a comment with the Qodana results summary to the pull request.
          post-pr-comment: true
          # Push Qodana fixes to the repository, can be none, branch to the
          # current branch, or pull-request (disabled as it fails build)
          # push-fixes: pull-request
